services:
  api:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgresql:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "alembic upgrade head && python -m pytest -v"
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy

  db-test:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: eventhub_test
    volumes:
      - postgresql_test:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d eventhub_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: ./backend

    command: alembic upgrade head

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    restart: "no"

volumes:
  postgresql:
    external: false
  postgresql_test:
    external: false
