name: Test AWS OIDC

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Check AWS identity
        run: aws sts get-caller-identity
